name: Build and Push Backend Image

on:
  push:
    branches:
      - dev                  # Promijenjeno na dev branch
    paths:
      - 'backend/**'         # Trigger samo na promjene u /backend direktoriju
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    env:
      BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          ref: dev          # Osigurava da povlači kod iz dev brancha

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
          cache-dependency-path: 'backend/pom.xml'

      - name: Maven build
        run: mvn clean package
        working-directory: backend  # Podesite ovo prema strukturi vašeg projekta

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend   # Osigurajte da je ovo točna putanja do Dockerfile-a
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      - name: Trigger release
        if: ${{ env.BACKEND_DEPLOY_HOOK }}
        run: curl ${{ env.BACKEND_DEPLOY_HOOK }}
